name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome
      run: |
        choco install googlechrome
        choco install chromedriver

    - name: Add Chrome to PATH
      run: |
        echo "C:\Program Files\Google\Chrome\Application" >> $env:GITHUB_PATH
        echo "C:\Program Files (x86)\Google\Chrome\Application" >> $env:GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest